# -*- coding: utf-8 -*-
"""CampusX_Week01_Session02_Operators-if-else-loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10RCdf3E27KJcACPTxRUrau_Y82xu13TQ

# **Operators in Python**
*   Arithematic Operators
*   Relational Operators
*   Logical Operators
*   Bitwise Operators
*   Assignment Operators
*   Membership Operators
"""

# Arithematic Operators:
# Operators: between two operands when you intend to do some changes. The thing you use between those operands is an operator. like to add to operands we use '+' operator
# 6 types of operators in Python
print("Addition Operator: ", 5+6)
print("Subtraction Operator: ", 5-6)
print("Multiplication Operator: ", 5*6)
print("Division Operator: ", 5/2)
print("Integer division Operator: ", 5//2) # integer division i.e. the quotient is always floored to nearest integer
print("Modulus Operator: ", 5%2) # modulus operator -> gives remainder
print("power of Operator: ", 5**2) # power of operator

# Relational Operators or comparision operators:
# used to compare two quantities we use these.
# Output of these operators is always True or False
print("greater than operator: ", 4>5)
print("less than operator: ", 4<5)
print("greater than equal to operator: ", 4>=5)
print("less than equal to operator: ", 4<=5)
print("equal to operator: ", 4==5)
print("not equal to operator: ", 4!=5)

# Logical operators
# used for logic  building
# three types and, or, not
print("0 and 0: ", 0 and 0)
print("1 and 0: ", 1 and 0)
print("0 and 1: ", 0 and 1)
print("1 and 1: ", 1 and 1)
print()
print("0 or 0: ", 0 or 0)
print("1 or 0: ", 1 or 0)
print("0 or 1: ", 0 or 1)
print("1 or 1: ", 1 or 1)
print()
print("not 0: ", not 0)
print("not 0: ", not 0)

# Bitwise operators
# operators that operate on binary values
# types: bitwise and -> &
print("bitwise and - 2 & 3: ", 2 & 3)
# types: bitwise or -> |
print("bitwise xor - 2 | 3: ", 2 | 3)
# types: bitwise xor -> ^ -> inputs are same output is 0
print("bitwise xor - 2 ^ 3: ", 2 ^ 3)
# types: bitwise not -> ~
print("bitwise xor - ~3: ", ~3)
# types: left shift : >>
print("bitwise xor - 4 >> 2: ", 4 >> 2)
# types: right shift : <<
print("bitwise xor - 5 << 2: ", 5 << 2)

# Assignment operators
# right side value is assigned to variable using assignment operator
# =
a = 2
print('a: ', a)

# +=
a += 2 # a = a + 2
print('a += 2: ', a)

# -=
a -= 2 # a = a - 2
print('a -= 2: ', a)

# *=
a *= 2 # a = a * 2
print('a *= 2: ', a)

# /=
a /= 2 # a = a / 2
print('a /= 2: ', a)

# %=
a %= 2 # a = a % 2
print('a %= 2: ', a)

# Membership Operator
# in -> -> whether a thing appears in bigger thing
# output of this is true
print("D" in "Delhi")
# not in ->
print("e" not in "Delhi")
print(1 in [2,3,4,5,6])

# Program - Find the sum of a 3 digit number entered by the user
number = int(input("Enter a 3 digit number: "))
print("Number: ", number)
sum = 0
# 345 % 10 -> 5
digit1 = number % 10
number //= 10

# 34 % 10 -> 4
digit2 = number % 10
number //= 10

# 3 % 10 -> 3
digit3 = number % 10
sum = digit1 + digit2 + digit3
print("Sum of digits: ", sum)

"""# **if-else in Python**"""

# login program and indentation
# program executes from top to bottom but sometimes that program has to execute option 1 and option i.e. called as branching
# suppose user entered his credentials. If credentials are correct we log in but if credentials are wrong we throw and error or ask to try again. -> branching in the program
# to handle branching we use if-else ....
# email: 'munish@gmail.com'
# password: 1234

email = input("Enter your email: ")
password = input("Enter your password: ")

## syntax
# if # condition:
#   # code
# else:
#   # code

## indentation ensure that code is beautifully writte
if email == 'munish@gmail.com' and password == '1234':
  print("Welcome")
else:
  print("Not correct")

# if - elif - else
# we use if - elif -else if there are more than two branches
# to code -> if email and password are correct then authenticate, if email is correct but password then give 2nd chance to login else show error

# email: 'munish@gmail.com'
# password: 1234

email = input("Enter your email: ")
password = input("Enter your password: ")

## indentation ensure that code is beautifully writte
if email == 'munish@gmail.com' and password == '1234':
  print("Welcome")
elif email == 'munish@gmail.com' and password != '1234':
  print("Incorrect password. Try again....")
  password = input("Enter your password again: ")
  if password == '1234': # nested if....
    print("Welcome")
  else:
    print("Beta tumse naa ho paayega!")
else:
  print("Not correct")

# if-else examples
# 1. Find the min of 3 given numbers
# 2. Menu Driven Program

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a < b and a < c:
  print(f"Number a: {a} is smaller than b: {b} and c: {c}")
elif b < c:
  print(f"Number b: {b} is smaller than a: {b} and c: {c}")
else:
  print(f"Number c: {c} is smaller than a: {a} and b: {b}")

# menu driven calculator
fnum = int(input("Enter the 1st number:"))
snum = int(input("Enter the 2nd number: "))

op = input("Enter the operation: ")

if op == '+':
  print("+ selected, adding: ", fnum + snum)
elif op == '-':
  print("- selected, subtracting: ", fnum - snum)
elif op == '*':
  print("* selected, multiplying: ", fnum * snum)
else: # if op /3 '*':
  print("last option implies / selected, dividing: ", fnum / snum)

menu = input("""
Hi! How can I help you.
1. Enter 1 from PIN change
2. Enter 2 for a balance check
3. Enter 3 for a withdrawl
4. Enter 4 for exiting
""")

if menu == "1":
  print("Pin Change")
elif menu == "2":
  print("Balance Check")
elif menu == "3":
  print("Withdrawl")
else:
  print("Exiting")

"""# **Modules in Python**

*   math
*   keyword
*   random
*   datetime

"""

# module is a pre-written function or utility that I call in my code. Promotes reusability.
# math
# contains all mathematical functions implemented
import math
print(math.factorial(5))
print(math.floor(6.7))
print(math.sqrt(196))

# keyword
# keywords are reserved keywords in python
import keyword
print(keyword.kwlist)

# random
# to generate random numbers
import random
print(random.randint(1,100))

# datetime
import datetime
print(datetime.datetime.now())

# So the import crashes, and because this happens inside Python’s introspection machinery, you get a cascade of confusing internal errors.
# This is not your code’s fault.
!pip install black isort
# !pip install "betterproto[compiler]"

# how to know inbuilt modules in python
help('modules') # -> after installing # "betterproto[compiler]"

"""# **Loops in Python**
*   Need for loops
*   While Loop
*   For Loop
"""

# Loop is an entity using which you can repeat same piece of code again and again
# two types - while loop and for loop

# while loop example - program to print the table
# Program - Sum of all the digits of a given number
# Program - Keep accepting numbers from users till he/she enters a 0 and then find the avg

# Pythontutor.com -> we can line by line debug the python code

# while loop example - program to print the table
number = int(input("Enter the number for which multiplication table is printed: "))
i = 1
while i <= 10:
  print(f"{number} * {i} = {number*i}")
  i += 1

# while loop with else
# in python we can use else with while loop also i.e. when while loop condition is false the code in else condition executes

x = 1
while x < 3:
  print(x)
  x += 1
else:
  print("Limit crossed with value of x: ", x)

# guessing game -
# 1. select a number between 1 and 100 and we call it jackpot number (say we guessed 50).
# 2. User to guess the number and if user guesses 60 we say to come down.
# 3. Next user to guess the smaller number and user guesses 40 and we so to go up.
# 4. Next user guesses 50 and we say he guessed in 3rd guess.

# generate a random integer between 1 and 100
import random

jackpot = random.randint(1, 100)

guess = int(input("Guess karo: "))

counter = 1
while guess != jackpot:
  if guess < jackpot:
      print("galat! Guess higher")
  else: # guess > jackpot:
      print("galat! Guess lower")

  guess = int(input("Guess karo: "))
  counter += 1
else:
  print("sahee guess kiya: ", jackpot)
  print("You took: ", counter, " attempts")

# Program - Sum of all the digits of a given number

number = int(input("Enter the number: "))
sum = 0
cache_number = number
while number != 0:
  sum += number % 10
  number //= 10

print (f"sum of digits of {cache_number} is {sum}")

# Program - Keep accepting numbers from users till he/she enters a 0 and then find the avg

sum = 0
number = int (input("Enter the number: "))
count = 0
while number != 0:
  count += 1
  sum += number
  number = int (input("Enter the number: "))
avg = sum / count
print(f"Average of entered {count} numbers is: ", avg)

# For loop demo
# for loop of python different from other for loop
# for loop of python is very powerful
# python for loop uses range: => Range will generate the number between given numbers
# in range we give two number where first number is included and 2nd number is excluded, i.e. range (a,n) will generate numbers from a to n-1. The third number in range gives increment step.
# in this for loop you don't need to give start condition, no terminate condition and no increment that you need to give in other languages


for i in range(1,11):
  print(i)

for i in range(1,16,3): # with step size of 3
  print(i)

for i in range(10,0,-1): # decrement loop so step size -1
  print(i, end=" ")

# can iterate over other data types
for i in "Delhi":
  print(i, end=" ")
# similarly can iterate of list, tuple, dictionaries ....

# iterate over a set
for i in {1,2,3,4,5,6,7,8}:
   print(i, end=" ")

"""# **Program**: The current population of a town is 10,000. The population of the town is increasing at the rate of 10% per year. You have to write a program to calculate the population after the end of 10 years."""

import math
current_population = 10000
for i in range(10,0,-1):
  current_population -= ((current_population * 10) / 100)
  print(f"Population for year {i}: {current_population}")
# print(math.Round(population, 0))
# print(int(population))

"""# **Sequence Sum**:
# 1/1! + 2/2! + 3/3! + ....
"""

import math
n = int(input("Enter the value of n: "))
sum = 0
for i in range (1, n+1):
  sum += (i / math.factorial(i))
print(sum)