# -*- coding: utf-8 -*-
"""session-1-tasks_Munish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uCl3w41KClfoTODsZSIK3qx2WhVvEcf

# Task : Session 1
Solve these questions own your own and try to test yourself what you have learned in the session.

Happy Learning!

### Q1 :- Print the given strings as per stated format.

**Given strings**:
```
"Data" "Science" "Mentorship" "Program"
"By" "CampusX"
```
**Output**:
```
Data-Science-Mentorship-Program-started-By-CampusX
```

Concept- [Seperator and End]
"""

# Write your code here
print("Data", "Science", "Mentorship", "Program", sep="-",end="-")
print("By", "CampusX", sep="-")

"""### Q2:- Write a program that will convert celsius value to fahrenheit."""

# Write your code here
temp_celsius = float(input("Enter the temperature in celsius: "))
temp_fahrenheit = (temp_celsius * 9 / 5) + 32
print(f"{temp_celsius} deg celsius = {temp_fahrenheit} deg fahrenheit")

"""### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax."""

# Write your code here
num1 = int(input("Enter number 1: "))
num2 = int(input("Enter number 2: "))
# python way
print ("python way: ", num1, num2, " swapped to ", num2, num1)
# mathematical way
print("Mathematical way -> before swapping: num1: ", num1, "num2: ", num2)
num1 = num1 + num2
num2 = num1 - num2
num1 = num1 - num2
print("Mathematical way -> after swapping: num1: ", num1, "num2: ", num2)

"""### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input."""

# Write your code here
x1 = int(input("Enter coordinate x1: "))
y1 = int(input("Enter coordinate y1: "))
x2 = int(input("Enter coordinate x2: "))
y2 = int(input("Enter coordinate y2: "))

euclidean_distance = ((x2-x1)**2 + (y2-y1)**2)**(1/2)
print(f"The euclidean distance between ({x1},{y1}) and ({x2},{y2}) is {euclidean_distance}")

"""### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

"""

# Write your code here
principle = int(input("Enter the principle amount: "))
rate_of_interest  = float(input("Enter the rate of interest: "))
time_period = int(input("Enter the time period: "))

simple_interest = principle * rate_of_interest * time_period / 100

print(f"the simple interest for principle: {principle} at given rate of interest :{rate_of_interest} for a time: {time_period} is: {simple_interest}")

"""### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

For example:
Input:
heads -> 4
legs -> 12
<br>
Output:
dogs -> 2
chicken -> 2




"""

# Write your code here
heads_count = int(input("Enter the number of heads: "))
legs_count = int(input("Enter the number of legs: "))
# chicken_x + dogs_y = heads_count
# 2 * chicken_x + 4 * dogs_y = legs_count
# 2 * (heads_count - dogs_y) + 4 * dogs_y = legs_count
# 2 * heads_count - 2 * dogs_y + 4 * dogs_y = legs_count
# 2 * dogs_y = legs_count - 2 * heads_count
dogs_y = (legs_count - 2 * heads_count) / 2
chicken_x = heads_count - dogs_y
print(f"dogs: {dogs_y}, chicken: {chicken_x}")

"""### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user."""

# Write your code here
n = int(input("Enter the value upto with sum of squares of first n numbers is to be calculated n: "))
sum_of_squares = n * ( n + 1) * (2*n + 1) / 6
print(f"sum of squares of first {n} numbers is {sum_of_squares}")

"""### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user."""

# Write your code here
first_term = int(input("Enter the first term of the arithematic series: "))
second_term = int(input("Enter the second term of the arithematic series: "))
n = int(input("Enter the value of n: "))
common_difference = second_term - first_term
nth_term = first_term + (n - 1) * common_difference
print(f"The {n}th term of the arithematic series is {nth_term}")

"""### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user."""

# Write your code here
first_nr = int(input("Enter numerator of first number: "))
first_dr = int(input("Enter denominator of first number: "))
second_nr = int(input("Enter numerator of second number: "))
second_dr = int(input("Enter denominator of second number: "))

common_denominator = first_dr * second_dr # ideally we need to take lcm.... but it is also ok ....
total_numerator = first_nr * second_dr + second_nr * first_dr
print(f"The sum of fractions {first_nr}/{first_dr} +  {second_nr}/{second_dr} = {total_numerator}/{common_denominator}")

"""### Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.



Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm
"""

# Write your code here
length_tank  = 20 # cm
width_tank  = 20 # cm
height_tank = 20 # cm
volume_of_tank = length_tank * width_tank * height_tank

height_glass = 3 # cm
radius_glass = 1 # cm
pi = 22 / 7
volume_glass = pi * (radius_glass**2) * height_glass
number_of_glasses = volume_of_tank / volume_glass

# fractional part makes no sense (for number of glasses) to truncating the decimal part
print(f"Number of glasses required to fill the tank: {int(number_of_glasses)}")