# -*- coding: utf-8 -*-
"""CampusX-Week01-Session01-BasicsOfPythonProgramming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cp2nZqaCLXXnVulWQ516P0ys6TowiNR_

## 1. **Python Output**
"""

# Python is a case sensitive language
print('Hello World')

# print number
print (7)

# print decimal
print(7.7)

# print boolean
print(True)

# multiple points
print("Hello", 1, 4.5, False)

print("Hello", 1, 4.5, False, sep='/')

print("Hello")
print("World")

print("Hello", end="-")
print("World")

"""## 2. **Data Types**"""

# Integer
print(8)
# 1 * 10^308
print(1e308)
# 1 * 10^309 # -> out of range....
print(1e309)

# decimal / float
print(8.55)
# 1.7 * 10^308
print(1.7e308)
# 1.7 * 10^309
print(1.7e309)

# Boolean
print(True)
print(False)

# Text / String
print('Hello String')

# complex number
print(5+6j)

# List
print([1, 2, 3, 4, 5, 6])

# Tuple
print((1, 2, 3, 4, 5, 6))

# Sets
print({1, 2, 3, 4, 5, 6})

# Dictionary
print({'name': 'Munish', 'age': 49, 'gender': "Male", 'weight': 78})

# type # -> type of a data
print(f'type("Hello World"): {type("Hello World")}')
print(f"type(88): {type(88)}")
print(f"type(8.8): {type(8.8)}")
print(f"type(False): {type(False)}")
print(f"type(6+7j): {type(6+7j)}")
print(f"type([1,2,3,4]): {type([1,2,3,4])}")
print(f"type((1,2,3,4)): {type((1,2,3,4))}")
print(f"type({1,2,3,4}): {type({1,2,3,4})}")
print(f"type({{'name': 'Munish', 'age': 49, 'gender': 'Male', 'weight': 78}}): {type({'name': 'Munish', 'age': 49, 'gender': 'Male', 'weight': 78})}")
person = {'name': 'Munish', 'age': 49, 'gender': 'Male', 'weight': 78}
print(f"type(person): {type(person)}")

"""## 3. **Variables**"""

# Static Vs Dynamic Typing
# Static Vs Dynamic Binding
# Stylish Declaration Techniques

name = 'Munish' # no need to show data type....
print (name)

a = 5
b = 6
print (a + b)

name1 = 'Munish'
blankspace = ' '
name2 = 'Sawhney'
print (name1 + blankspace + name2)

# '+' used to add for two numbers
# '+' used to concatenate two strings / text

# Dynamic Typing
# you do not tell the type of variable. Python automatically infers type
# you need to tell the type of variable like C/ C++ / Java

# Dynamic binding -> supported by python
a = 5
print (a, type(a))
a = 'Munish'
print (a, type(a))

# Static binding -> supported by c / c++ / java
# cannot change the type once assigned

# Dynamic binding -> supported by python

a = 1
b = 2
c = 3
print(a,b,c)

# Stylish Declaration Techniques
a,b,c = 1,2,3
print(a,b,c)
print(a,b)
print(b,a)

same_value_var1=same_value_var2=same_value_var3 = 5
print(same_value_var1, same_value_var2, same_value_var3)

"""**Comments**"""

# this is a comment
a = 5 # assigned 5 to a
b = 6 # assigned 6 to b

print(a + b) # adds a and b and prints the sum...

# can write comments on top of the line or or side....

"""4. **Keywords & Identifiers**"""

# Keywords
# reserved words by python which are understood by python compiler.
# 32 words are python compiler. don't use them them as variable name.

# Identifiers
# names created in program are identifiers
# identifiers eg. function names, class names, variables etc.
# rules for creating identifiers:
#  1. cannot start the name with a digit but digit and come in end or middle
#  2. use uppercase, lowercase, digits but in special case use just '_' (underscore)
#     eg. even _ can be a variable name.
#  3. identifier names cannot be keywords names.

"""5. **User Input**"""

# two types of softwares - static softwares and dynamic softwares
# static softwares: we just seek information eg. calendar, clock, blogs, college website (just taking information)
# dynamic softwares: interactive eg. youtube, facebook, ola, zomat0. 99% s/wares are dynamic
# - important aspect of dynamic softwares is that we should be able to take input from user.

# - in python we use function 'input' to take input from the user.

input('Apna naam bataa: ')
input('Enter email: ')

# Take input from users and store them in a variable
# add the two variables and store result in 3rd variable result
# print the result

fnum = input("Enter the 1st number: ")
snum = input("Enter the 2nd number: ")
print(f"fnum: {fnum} and type(fnum): {type(fnum)}")
print(f"snum: {snum} and type(snum): {type(snum)}")
result = fnum + snum
print(f"result: {result}")

# because string is the universal format to store inputs

"""# 6. **Type Conversion**"""

# in type conversion the variable is not permanently converted but in typecasting the varialbe is permanently converted.
# Implicit type conversion vs Explicit type conversion
# Implicit type conversion = compiler automatically converts the type
# eg....
print (5 + 5.6)
print (type(5), type(5.6), type(5 + 5.6))
# 5 is implicitly converted to float

# eg. print(4 + '4') -> gives error as int and str are incompatible

# explict type conversion
# str -> int
# type conversion is possible if it is possible
print(type(int('4')))
print(type(complex('4+5j')))
print(type(str(5)))

fnum = input("Enter the 1st number: ")
snum = input("Enter the 2nd number: ")
print(f"fnum: {fnum} and type(fnum): {type(fnum)}")
print(f"snum: {snum} and type(snum): {type(snum)}")
result = int(fnum) + int(snum)
print(f"result: {result}")
print(f"fnum type: {type(fnum)}")

"""# 7. **Literals**




"""

# What ever raw value is stored is called as Literal.

a = 0b1010 # Binary Literal
b = 100  # Decimal Literal
c = 0o310 # Octal Literal
d = 0x12c # Hexadecimal Literal
print(a, b, c, d)

# Float Literal
float_1 = 10.5
float_2 = 1.5e2 # 1.5 * 10^2
float_3 = 1.5e-3  # 1.5 * 10^-3

# Complex Literal
x = 3.14j
print(x.real, x.imag)

# string literals
string = 'This is Python'
strings = "This is Python"
char = "C"
multiline_str = """This is a multiline string with more than one line code."""
unicode = u"\U0001f600\U0001F606\U0001F923"
raw_str = r"raw \n string"

print(string)
print(strings)
print(c)
print(multiline_str)
print(unicode)
print(raw_str)

# python treats booleans as integers
# True is interpreted as 1
# False is interpreted as 0
a = True + 4
b = False + 10

print("a: ", a, type(a))
print("b: ", b, type(b))

a = None
print (a, type(a))

# in python there is no way you can declare a variable (because of dynamic type inferance)
# so we declare that variable as None

"""#8. **Operators**"""

# Arithematic
# Relational
# Logical
# Bitwise
# Assignment
# Membership

"""# 9. **if-else**"""